global using HealthChecks.UI.Client;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Primitives;
global using NSwag;
global using Serilog;
global using Serilog.Context;
global using Serilog.Events;
