version: "3.8"

services:
  gateway:
    build:
      context: ./gateway/src/Gateway.Web
    ports:
      - "5000:5000"
    depends_on:
      - service-dotnet
      - service-python
    networks:
      - internal

  service-dotnet:
    build:
      context: ./microservices/users-service/src/UsersService.Web
    ports:
      - "6000:6000"
    networks:
      - internal

  service-golang:
    build:
      context: ./microservices/metrics-service/src/MetricsService
    ports:
      - "7000:7000"
    networks:
      - internal

  service-python:
    build:
      context: ./microservices/reports-service
    ports:
      - "8000:8000"
    networks:
      - internal

networks:
  internal:
    driver: bridge
